### ISSUE TITLE
Problems with CMakeLists

### ISSUE THREAD

**Issue by MKZwei** [cycfi/q#11]
I can’t compile your library Q-master in Android Studio. The error message is: ERROR: /Users.../CMakeLists.txt : C/C++ debug|x86 : CMake Error at /Users.../CMakeLists.txt:15 (add_subdirectory):add_subdirectory given source „../infra“ which is not an existing directory.

I’m kinda of new in this subject. Could you check the Error message please?

**Comment by djowel** [comment]
I haven't tested on android, but perhaps the Setup and Installation should help:
https://github.com/cycfi/Q/blob/master/docs/setup.md

(esp. for infra)

**Comment by MKZwei** [comment]
Hello, it finally worked out. I downloaded the infra library and added it to the directory of the Q DSP library. I just had to renew the path to infra in the CMakeLists.txt file. Given the path on my computer.
Thanks a lot for the help

**Comment by KingZD** [comment]
> 

Hello, I also tried to compile in Android studio, but failed. How do you configure CMakeLists.txt.  Thanks!

**Comment by KingZD** [comment]
> Hello, it finally worked out. I downloaded the infra library and added it to the directory of the Q DSP library. I just had to renew the path to infra in the CMakeLists.txt file. Given the path on my computer. Thanks a lot for the help

Hello, I also tried to compile in Android studio, but failed. How do you configure CMakeLists.txt. Thanks!
