### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by fpesari** [cycfi/q#13]
Hello,

first, this library is really awesome! It really makes DSP effortless.

I wonder if releases are possible, so that it's easier for developers (and packagers) to refer to a specific version of Q.

**Comment by djowel** [comment]
Thank you very much! I'll be working more on Q in the coming days, so I'll keep this in mind and make a release as soon as I can.

**Comment by djowel** [comment]
Working on the docs now, towards a 1.0 release: https://cycfi.github.io/q/

**Comment by redtide** [comment]
where the release?

**Comment by djowel** [comment]
> where the release?

not yet. almost there.
