### ISSUE TITLE
Implementing Q_Lib with Juce - Linker errors

### ISSUE THREAD

**Issue by benediktadams** [cycfi/q#2]
Hey,

As described earlier through facebook, I'm trying to implement Q_Lib with Juce. 

I included search paths for infra and q_lib into an empty Juce Project and included `pitch_detector.hpp` into my Juce main class. 

A few errors happen after that. 

1. q/support/base.hpp: 
The two last functions in the script (`abs_within()`, `relwithin()`) call `std::abs()`. Xcode reports that the call to abs is ambiguous. 
I "fixed" it by removing the `std::` to make it use the namespace’s own `constexpr abs()`… bad fix probably?  

2. q/utility/zero_crossing.hpp: 
Doesn’t know type `decibel`. 
My probably bad fix: included` <q/support/decibel.hpp>` into `zero_crossing.hpp`

After that no more errors in the scripts, but the attached linker errors show up.
What I can read from this is that there are duplicate symbols for the following functions:

```
count_bits()(in q/detail/count_bits.hpp) 
autocorreclate() (in q/pitch/period_detector.hpp)
predict_period() (in q/pitch/period_detector.hpp)
```

Any idea how I can tackle this? Or am I even the one causing these through my assumingly hacky fixes described above? 

Here are the linker errors as reported by Xcode
```
duplicate symbol __ZN5cycfi1q6detail10count_bitsEy in:
    /Users/benediktsailer/Library/Developer/Xcode/DerivedData/PitchDetection-cftahhuurjbgrrfhpqyoqkkcntwm/Build/Intermediates.noindex/PitchDetection.build/Debug/PitchDetection - App.build/Objects-normal/x86_64/MainComponent.o
    /Users/benediktsailer/Library/Developer/Xcode/DerivedData/PitchDetection-cftahhuurjbgrrfhpqyoqkkcntwm/Build/Intermediates.noindex/PitchDetection.build/Debug/PitchDetection - App.build/Objects-normal/x86_64/Main.o
duplicate symbol __ZN5cycfi1q15period_detector13autocorrelateEv in:
    /Users/benediktsailer/Library/Developer/Xcode/DerivedData/PitchDetection-cftahhuurjbgrrfhpqyoqkkcntwm/Build/Intermediates.noindex/PitchDetection.build/Debug/PitchDetection - App.build/Objects-normal/x86_64/MainComponent.o
    /Users/benediktsailer/Library/Developer/Xcode/DerivedData/PitchDetection-cftahhuurjbgrrfhpqyoqkkcntwm/Build/Intermediates.noindex/PitchDetection.build/Debug/PitchDetection - App.build/Objects-normal/x86_64/Main.o
duplicate symbol __ZNK5cycfi1q15period_detector14predict_periodEv in:
    /Users/benediktsailer/Library/Developer/Xcode/DerivedData/PitchDetection-cftahhuurjbgrrfhpqyoqkkcntwm/Build/Intermediates.noindex/PitchDetection.build/Debug/PitchDetection - App.build/Objects-normal/x86_64/MainComponent.o
    /Users/benediktsailer/Library/Developer/Xcode/DerivedData/PitchDetection-cftahhuurjbgrrfhpqyoqkkcntwm/Build/Intermediates.noindex/PitchDetection.build/Debug/PitchDetection - App.build/Objects-normal/x86_64/Main.o
duplicate symbol __ZN5cycfi1q6detail10count_bitsEj in:
    /Users/benediktsailer/Library/Developer/Xcode/DerivedData/PitchDetection-cftahhuurjbgrrfhpqyoqkkcntwm/Build/Intermediates.noindex/PitchDetection.build/Debug/PitchDetection - App.build/Objects-normal/x86_64/MainComponent.o
    /Users/benediktsailer/Library/Developer/Xcode/DerivedData/PitchDetection-cftahhuurjbgrrfhpqyoqkkcntwm/Build/Intermediates.noindex/PitchDetection.build/Debug/PitchDetection - App.build/Objects-normal/x86_64/Main.o
ld: 4 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by djowel** [comment]
- The linker errors should be fixed now. 
- Including the <q/support/decibel.hpp> in zero_crossing.hpp is correct
- I am not so sure about abs(). A direct qualification to std should not case ambiguity. But your fix is safe. Could you tell me the exact error message if you revert your "fix"?

**Comment by benediktadams** [comment]
Awesome, I haven't coded anything yet, but my project now builds with Q_Lib included and ready to go. 

The ambiguity with the std qualification startled me too... no idea why this could be happening, so I took some screenshots for you, hope they help. 

![image](https://user-images.githubusercontent.com/20302171/57978300-ea428380-7a0a-11e9-8fe7-70d03da6cb63.png)

The candidate functions:
![image](https://user-images.githubusercontent.com/20302171/57978309-12ca7d80-7a0b-11e9-8e0c-65fc64161a35.png)

![image](https://user-images.githubusercontent.com/20302171/57978313-1eb63f80-7a0b-11e9-970c-b9cfae5edd76.png)

I'm going to attempt to write a juce wrapper for QLib now.... Thanks for the help!

**Comment by djowel** [comment]
> The ambiguity with the std qualification startled me too... no idea why this could be happening, so I took some screenshots for you, hope they help.

It will be better if you just post the actual error text.

**Comment by benediktadams** [comment]
The actual error text is what you see on the first screenshot on the first line. This is also what Xcode shows in the red bubble on both lines using the std::abs function (the last 2 functions in base.hpp)

> Call to 'abs' is ambiguous

Or is that not what you mean by error text?

**Comment by djowel** [comment]
I mean text instead of picture, but nevermind, I pushed the workaround that uses q::abs instead of std::abs.

**Comment by benediktadams** [comment]
Ah sorry, yeah makes sense... 

Awesome, that means QLib is now compatible with Juce "out of the box", which is amazing since it greatly extends Juce's capabilities.Thanks a lot for taking the time for this!
