### ISSUE TITLE
midi processor dispatch() not catching notes on channels other than 0

### ISSUE THREAD

**Issue by unlessgames** [cycfi/q#22]
When running the midi_monitor example, I noticed it only registers midi events as note on/off  if they are coming in on the first midi channel.

**Comment by djowel** [comment]
I'm sorry I missed this, and it took so long. This is fixed now in develop and master. Silly bug! So simple: 
https://github.com/cycfi/q/commit/86685e26b2a9d5f661b68fb2fed0401070ff29d9
