### ISSUE TITLE
Mac os 11.2 needs latest portaudio for running

### ISSUE THREAD

**Issue by torgeir** [cycfi/q#29]
Hey,

Thanks for a great library!

It seems however that building and running the examples on a modern mac needs some of the latest stuff from portaudio master https://github.com/PortAudio/portaudio instead of the currently used sha from the head of the submodule @09087cf5a63d6fdb6aca139331f017da970f8177, which is behind

```
[submodule "q_io/external/portaudio"]
	path = q_io/external/portaudio
	url = https://git.assembla.com/portaudio.git
```

Currently most examples are failing with

```sh
❯ example/example_sin_synth
||PaMacCore (AUHAL)|| Error on line 1316: err='-66748', msg=Unknown Error
```

Is there a reason for using portaudio from git.assembla.com instead of the github one?

Would you care to update the portaudio submodule to include its latest commits from master, or would you accept a PR that moves to the head portaudio from github?

Regards
Torgeir

**Comment by djowel** [comment]
The develop branch already uses the latest from github. I will update master later.

**Comment by djowel** [comment]
Done. Please check master again. Please tell me if you still have problems. If all is good, feel free to close this issue.

**Comment by torgeir** [comment]
Oh, I didn't catch that! Current master works like a charm 👌  Thanks.
