### ISSUE TITLE
Are you looking for contributors?

### ISSUE THREAD

**Issue by BennetLeff** [cycfi/q#3]
This project looks great. There haven't been any commits in a few months so I wanted to first ask if this project is still in development? If so, are you looking for contributors? Finally, if you are open to help, is there any area in particular?

**Comment by djowel** [comment]
Yeah, I've been busy with the Photon/Elements project and QPlug (not yet public). What areas are you interested in? I'd probably say that I need to work on the docs, but typically folks don't want to work on the boring stuff ;-).

**Comment by BennetLeff** [comment]
I could probably help with docs after getting a bit better acquainted with the library. I'll be playing around with the library for now. If there are specific goals/tasks to accomplish I'm interested in contributing :)

**Comment by djowel** [comment]
> I could probably help with docs after getting a bit better acquainted with the library. I'll be playing around with the library for now. If there are specific goals/tasks to accomplish I'm interested in contributing :)

Thank you very much for your interest! Now I need to figure out the bast way to communicate. There's slack, of course. But I am not sure everyone knows about it. Do you? I'm not sure what's the best way to communicate in this github world. Github issues seems rather odd as a communication medium, does Github really endorse that? https://ben.balter.com/2014/11/06/rules-of-communicating-at-github/ <shrug>

**Comment by BennetLeff** [comment]
Slack may be the best way. I have seen projects use github issues for some communication. Github issues are public which can help others who are interested. However, it's definitely not an ideal communication method. Perhaps there's a better option than Slack but I'm not aware of one.

**Comment by djowel** [comment]
So follow [this Slack link](https://join.slack.com/t/cycfi/shared_invite/enQtNzI2NTAzNjYxNDg5LTU3YTU3MWE1Y2Q4MjQyNzAwYjIxMTFjMzBjZjM3ZTg1ZGY1YWFiY2FkNWU5NmU5YjMzMWFmOGFjNzExYWQ0MjI).

There will be some action here, hopefully soon. Right now, I'm busy with the [Elements GUI library](https://www.cycfi.com/2019/07/photon-micro-gui/) (among other things).

**Comment by djowel** [comment]
I value meaningful discussions, and I am very open to collaboration. I invite you to join our mailing list so we can discuss plans, and ongoing developments. https://groups.google.com/forum/#!forum/cycfi-discuss/join

**Comment by rghvdberg** [comment]
> So follow [this Slack link](https://join.slack.com/t/cycfi/shared_invite/enQtNzI2NTAzNjYxNDg5LTU3YTU3MWE1Y2Q4MjQyNzAwYjIxMTFjMzBjZjM3ZTg1ZGY1YWFiY2FkNWU5NmU5YjMzMWFmOGFjNzExYWQ0MjI).
> 
can you post a new invite link ? this one no longer works

**Comment by djowel** [comment]
> can you post a new invite link ? this one no longer works

Yes, that is no longer relevant. Use the google link instead. I'll probably have a dedicated google group for Q when there's enough momentum.
