### ISSUE TITLE
= operator overload

### ISSUE THREAD

**Issue by propeller3D** [cycfi/q#63]
Hello! I have a question about the = operator overload in the dc_block struct. Why does it take a boolean argument _y and assign it to the object? It’s not clear why this is done. Forgive me if the question is stupid because my c++ skills are limited and I’m still learning.

**Comment by djowel** [comment]
THAT is wrong. You caught a bug! Your c++ skills saved the day!

Would you like to do a PR? Should be an easy one. The `bool` must be a `float` which follows the documentation:

a = s : Set the latest result to s.

**Comment by propeller3D** [comment]
Happy to contribute. I’ll do it. I have never done a pull request so please allow me a day or so to do the proper research so I can do it properly. I’m studying your code style, it’s very nice. I’m trying to adapt some of it in my own code.

**Comment by djowel** [comment]
> I’m studying your code style, it’s very nice. I’m trying to adapt some of it in my own code.

Very glad you liked it!

**Comment by djowel** [comment]
Fixed in #64
