### ISSUE TITLE
Non-existent folder for infra library

### ISSUE THREAD

**Issue by hosack** [cycfi/q#7]
When trying to run cmake get the following error:
```
CMake Error at CMakeLists.txt:15 (add_subdirectory):
  add_subdirectory given source "../infra" which is not an existing
  directory.
```
It looks like the infra library is missing from the repo.

**Comment by djowel** [comment]
Did you follow the installation guide? https://github.com/cycfi/Q/blob/master/docs/setup.md (see the Git section in particular).

**Comment by hosack** [comment]
Read the manual... why would I do that?! :).  I feel stupid but it's working now. Thanks.

**Comment by djowel** [comment]
> Read the manual... why would I do that?! :). I feel stupid but it's working now. Thanks.

There might be a way to make it automatic using cmake, or at the very least issue an error with a suggestion on how to make it work. I'll see what I can do.

**Comment by hosack** [comment]
Since I'm new to this library I wasn't sure what infra was.  I'm familiar with portaudio and portmidi so I new what to do with those libraries.  Perhaps you could treat infra as an external library like portaudio and users can add it using the `git submodule init` command.  Then the toplevel CMakeLists.txt could include infra in the same way it includes the port* libraries.

**Comment by djowel** [comment]
> Since I'm new to this library I wasn't sure what infra was. I'm familiar with portaudio and portmidi so I new what to do with those libraries. Perhaps you could treat infra as an external library like portaudio and users can add it using the `git submodule init` command. Then the toplevel CMakeLists.txt could include infra in the same way it includes the port* libraries.

Except that Infra is also used by other Cycfi libraries such as Elements and many more and I had to avoid having duplicate submodules in different sub-directories.
