### ISSUE TITLE
dynamic_smoother has one cycle of latency

### ISSUE THREAD

**Issue by thirtythreeforty** [cycfi/q#74]
https://github.com/cycfi/q/blob/73d2b939d9d7e2b6e92ef7b8fb7d67683286ca15/q_lib/include/q/fx/lowpass.hpp#L241

This line does not match the original paper, which returns `low2` immediately. Instead, Q's implementation will return the $z^{-1}$ delayed version.

If this is intentional, it's worth a comment. I don't see any benefit; it looks like a typo.

**Comment by djowel** [comment]
Good catch. Care to submit a PR?
