### ISSUE TITLE
So is this the way to phase/shift 180 a signal, for example?

### ISSUE THREAD

**Issue by WindowsNT** [cycfi/q#8]
This sounds promising - I'm looking to implement phase shifting using your all pass. Let's say I want an 180 shift at a float[] buffer with a sz size:

`
 auto ph = cycfi::q::phase(3.1415f);

 for (int i = 0 ; i < sz ; i++)
   {
      auto out = q::sin(ph);
      buff[i] += out;
   }
`

Does that seem correct?

Thanks.

**Comment by djowel** [comment]
First of all, phase is used for synthesis, not for phase shifting the all pass. Could you elaborate what you intend to do? 

As for phase-shifting oscillators (for synthesis) phase is doc'd here: https://github.com/cycfi/Q/blob/master/q_lib/include/q/support/phase.hpp#L18 

The constructor taking in float assume fractional phase, normalized from 0 to 1.0, which corresponds to 0 to 2π. So you'll probably want phase(0.5).

**Comment by djowel** [comment]
See "Turn" here: https://en.wikipedia.org/wiki/Angular_unit

**Comment by WindowsNT** [comment]
Thanks for the normalization tip.  I'm trying to turn the phase of an existing audio float buffer, not to synthesize new data.

**Comment by djowel** [comment]
You need the allpass arlight: https://github.com/cycfi/Q/blob/master/q_lib/include/q/fx/allpass.hpp#L16

// 90 deg shift at frequency f

**Comment by WindowsNT** [comment]
Thanks a lot. I'm planning to put this as a phase shifting tool in my sequencer.
