### ISSUE TITLE
pitch detection example

### ISSUE THREAD

**Issue by lokkiikkol** [cycfi/q#9]
hi there, not really an issue... i am interested in porting/implementing your pitch detection method and possibly the onset detector to axoloti (a dsp platform) i can read and understand a little c code, but i am a bit lost with your code :-) is one of the files here already a working pitch extraction example? or is this just the library? thanks for your work!

**Comment by djowel** [comment]
I'm sorry, but the library requires knowledge of modern c++.

**Comment by lokkiikkol** [comment]
i see, do you think someone with that knowledge could make it run on the
axoloti? (stm f4) is it lightweight enough?

thanks

**Comment by djowel** [comment]
That's the idea, yes. People are already using it on small MCUs.

**Comment by lokkiikkol** [comment]
perfect thanks.
